[development]
dynaconf_merge = true

[development.db]
echo = true

[development.server]
log_level = "debug"
reload = true

[production]
dynaconf_merge = true

[production.db]
echo = false

[production.server]
log_level = "error"
reload = false
